<?xml version="1.0"?> 
<!-- Revolute-Revolute Manipulator -->
<robot name="rrbot"
  xmlns:xacro="http://www.ros.org/wiki/xacro"
  xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller">

  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="width" value="0.1" />
  <xacro:property name="height1" value="2" />
  <xacro:property name="height2" value="1" />
  <xacro:property name="height3" value="1" />
  <xacro:property name="axel_offset" value="0.05" />

  <link name="world"/>

  <link name="link1">
    <collision>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height1}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height1}"/>
      </geometry>
      <material name="red">
	<color rgba="0.6 0 0 1.0"/>
      </material>
    </visual>

    <inertial>
      <origin xyz="0 0 1" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia 
        ixx="1.0" ixy="0.0" ixz="0.0" 
        iyy="1.0" iyz="0.0" 
        izz="1.0"/>
    </inertial>
  </link>

  <link name="link2">
    <collision>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry> 
	<box size="${width} ${width} ${height2}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry> 
	<box size="${width} ${width} ${height2}"/>
      </geometry>
      <material name="green">
	<color rgba="0 0.6 0 1.0"/>
      </material>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia 
        ixx="1.0" ixy="0.0" ixz="0.0" 
        iyy="1.0" iyz="0.0" 
        izz="1.0"/>
    </inertial>
  </link>

  <link name="link3">
    <collision>
      <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
      <geometry> 
	<box size="${width} ${width} ${height3}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
      <geometry> 
	<box size="${width} ${width} ${height3}"/>
      </geometry>
      <material name="blue">
	<color rgba="0 0 0.6 1.0"/>
      </material>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia 
        ixx="1.0" ixy="0.0" ixz="0.0" 
        iyy="1.0" iyz="0.0" 
        izz="1.0"/>
    </inertial>
  </link>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="link1"/>
  </joint>

  <joint name="joint1" type="continuous">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 ${width} ${height1 - axel_offset}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <joint name="joint2" type="continuous">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="0 ${width} ${height2 - axel_offset*2}" rpy="0 0 0"/> 
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>

</robot>
